site_name: "Technology Blog"
site_description: "努力挺进去"
site_author: "NoNo"
site_url: https://navi-nanxiqi.github.io/tech-blog/

# Repository
repo_name: tech-blog
repo_url: https://github.com/navi-nanxiqi/tech-blog

# Theme
theme:
  name: material
  language: zh
  palette:
    # 浅色模式
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # 深色模式  
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.path

# Plugins
plugins:
  - search:
      lang: 
        - zh
        - en
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition # 便利贴
  - pymdownx.details # 块折叠
  - pymdownx.inlinehilite # 块嵌套
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Navigation
nav:
  - 首页: index.md
  - 技术文章:
    - Python:
      - pages/python/index.md
      - pages/python/1test.md
    - JavaScript:
      - pages/javascript/index.md
    - Docker:
      - pages/docker/index.md
    - 数据库:
      - pages/database/index.md
    - Nginx:
      - pages/nginx/index.md
    - FastApi:
      - pages/fastapi/index.md
  - 工具分享: tools/index.md
  - 关于: about.md

# Extra CSS
extra_css:
  - common/stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - common/javascript/extra.js

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
    - icon: fontawesome/solid/envelope
      link: mailto:your.email@example.com
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # 替换为您的 Google Analytics ID
  generator: false
  version:
    provider: mike

# Copyright
copyright: Copyright &copy; 2025 technology-notes | Built with MkDocs Material