site_name: 技术博客
site_description: 个人技术博客，分享编程经验和技术心得
site_author: 博主
site_url: https://navi-nanxiqi.github.io/tech-blog/

# Repository
repo_name: tech-blog
repo_url: https://github.com/navi-nanxiqi/tech-blog

# Theme
theme:
  name: material
  language: zh
  palette:
    # 浅色模式
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # 深色模式  
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search:
      lang: 
        - zh
        - en
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            首页: Home
            技术文章: Technical Articles
            Python: Python
            JavaScript: JavaScript
            数据库: Database
            工具分享: Tools
            关于: About

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Navigation
nav:
  - 首页: index.md
  - 技术文章:
    - Python: python/index.md
    - JavaScript: javascript/index.md
    - 数据库: database/index.md
  - 工具分享: tools/index.md
  - 关于: about.md

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
    - icon: fontawesome/solid/envelope
      link: mailto:your.email@example.com
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # 替换为您的 Google Analytics ID
  generator: false
  version:
    provider: mike

# Copyright
copyright: Copyright &copy; 2024 技术博客 | Built with MkDocs Material