name: 部署MkDocs到GitHub Pages

on:
  push:
    branches:
      - main  # 设置为您的默认分支
  workflow_dispatch:  # 允许手动触发工作流

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 构建并部署
        run: |
          mkdocs gh-deploy --force